# Generated by Django 6.0.3 on 2026-03-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('temple', 'Temple'), ('hidden_spots', 'Hidden Spots'), ('falls', 'Waterfalls'), ('food', 'Food')], default='temple', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(choices=[('pollachi', 'Pollachi'), ('coimbatore', 'Coimbatore'), ('trichy', 'Trichy'), ('chennai', 'Chennai')], default='coimbatore', max_length=20),
        ),
    ]
