# Generated by Django 6.0.3 on 2026-03-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    
    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
    ]
