# Generated by Django 6.0.3 on 2026-03-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
    ]
