# Generated by Django 6.0.3 on 2026-03-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
